\documentclass{article}

\begin{document}

<<>>=
y<-c(1,0,0,0,0,0,0,1,0,0,0,0)
N<-length(y)
N_start=2;
N_end=2;
N_ones=0;
N_zeros=0;
@

<<>>=
library("rstan");
rstan_options(auto_write = TRUE)
options(mc.cores = parallel::detectCores())

stanfit <- stan("Bernoulli_example.stan",iter=20000)
print(stanfit);
print(get_stanmodel(stanfit))
@

<<>>=
library("shinystan")
launch_shinystan(stanfit)
@

\end{document}